---
- name: Helm - Install required system packages
  apt:
    state: latest
    update_cache: yes
    name:
      - curl 
      - gpg
      - apt-transport-https


- name:  Helm - Install the Helm GPG key.
  ansible.builtin.get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    dest: /tmp/helm.asc

- name: Helm - dearmor the downloaded signing key file
  shell: gpg --batch --dearmor -o /usr/share/keyrings/helm.gpg /tmp/helm.asc
  args:
    creates: /usr/share/keyrings/helm.gpg

- name: Helm - Add the Repo Helm
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main
    state: present
    filename: helm-stable-debian

- name: Helm - Install Helm
  apt:
    state: present
    update_cache: true
    name:
    - helm 

