---
- name: Install required system packages
  apt:
    state: latest
    update_cache: yes
    name:
      - gnupg
      
- name:  download the package signing key for the HashiCorp Debian repository.
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp-archive-keyring.asc
    checksum: "sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029" 

- name: dearmor the downloaded signing key file
  shell: gpg --batch --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp-archive-keyring.asc
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add the official HashiCorp repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64, signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_facts["lsb"]["codename"] }} main
    state: present
    filename: hashicorp

- name: Install vagrant.
  apt:
    state: present
    update_cache: true
    name:
    - vagrant
